### ISSUE TITLE
View request XML before sending?

### ISSUE THREAD

**Issue by MikkyX** [mrmarkfrench/silverpop-php-connector#28]
Is it possible to view the XML before sending it using the SilverpopXmlConnector? IBM are asking for a sample request to help us debug an issue - but we build the request using an object and then pass it straight to your connector to send.

**Comment by mrmarkfrench** [comment]
Sorry for the crazy delay on responding here. The notification fell through the cracks and I didn't see you'd asked the question until I was clearing out my inbox.

I'm sure you've resolved this one way or the other by now, but for the sake of having an answer here if anybody else has a similar question:

You can intercept an outgoing XML request in the `post` method of `SilverpopXmlConnector`, which is on line 1058. That method will have the fully-constructed XML element on-hand, and you can use the `asXML` method on the object to get the XML as a string. In fact, on line 1061, the library is already doing that for you. You can write that string to your logs (or wherever else) as needed. If you need the version including the envelope, you can use the variable generated on line 1068, instead.
